'use strict';

// Схема брифа для селлера маркетплейсов (WB / Ozon / Я.Маркет).
// Источник правды для UI и валидации. Markdown — справочный документ для людей.

module.exports = {
  type: 'seller',
  title: 'Бриф для запуска ФК',
  type_title: 'СЕЛЛЕР',
  intro: 'Бриф для селлера маркетплейсов. Если вы эксперт, агентство или продаёте услуги — напишите Никите в Telegram, пришлёт правильную ссылку.',
  thanks: 'Изучу ответы и в течение 1 рабочего дня пришлю стратегию и контент-план первого месяца на согласование.',
  steps: [
    {
      key: 'contacts',
      label: 'Контакты',
      title: 'Контактные данные',
      description: 'Куда прислать стратегию и материалы. Если поле уже заполнено — можно оставить как есть.',
      fields: [
        { kind: 'text', name: 'email', type: 'email', label: 'Email для отправки стратегии и материалов', placeholder: 'you@example.com' },
        { kind: 'text', name: 'telegram', label: 'Telegram (если отличается от первичной заявки)', placeholder: '@username' },
        { kind: 'text', name: 'call_time', label: 'Удобное время для созвонов', placeholder: 'например — будни 10:00–13:00 МСК' },
      ],
    },
    {
      key: 'brand',
      label: 'Раздел 1',
      title: 'Бренд',
      fields: [
        { kind: 'text', name: 'brand_name', label: 'Название бренда', required: true },
        { kind: 'text', name: 'brand_what_sell', label: 'Что продаёте (одной фразой)', placeholder: 'например — повседневная женская одежда из натуральных тканей' },
        { kind: 'radio', name: 'brand_years_on_market', label: 'Сколько лет на рынке', grid: 2,
          options: ['менее 1 года', '1–2 года', '3–5 лет', '5+ лет'] },
        { kind: 'checkbox', name: 'brand_marketplaces', label: 'Маркетплейсы', grid: 2,
          options: ['Wildberries', 'Ozon', 'Яндекс.Маркет'], otherText: 'другое — укажите' },
        { kind: 'radio', name: 'brand_personality', label: 'За брендом стоит личность или компания без лица?',
          hint: 'От этого зависит формат: от первого лица (истории, голос основателя, лайфстайл) или от бренда (продуктовый, экспертный, без персоны).',
          grid: 1,
          options: [
            { value: 'Личный бренд', label: 'Личный бренд (основатель/лицо ведёт блог)' },
            { value: 'Корпоративный', label: 'Корпоративный (без конкретного лица)' },
            { value: 'Гибрид', label: 'Гибрид (есть лицо, но не главное)' },
          ],
          extra: { kind: 'text', name: 'brand_face_info', placeholder: 'Если личный — кто (имя, должность)' } },
        { kind: 'textarea', name: 'brand_history', label: 'Краткая история — как и почему вы открыли этот бизнес', hint: '2–3 предложения, не лозунги.' },
      ],
    },
    {
      key: 'customer',
      label: 'Раздел 2',
      title: 'Покупатель',
      fields: [
        { kind: 'text', name: 'customer_demographics', label: 'Пол / возраст / доход (диапазоны)', placeholder: 'например — женщины 28–40 лет, доход 80–200 тыс/мес' },
        { kind: 'radio', name: 'customer_geography', label: 'География', grid: 2,
          options: ['вся Россия', 'только города-миллионники', 'регионы', 'другое'],
          otherText: 'другое — укажите' },
        { kind: 'text', name: 'customer_lifestyle', label: 'Образ жизни (1–2 маркера)', placeholder: 'например — работающие мамы / IT-специалисты / тренируются в зале' },
        { kind: 'text', name: 'customer_problem', label: 'Какую проблему/задачу решает ваш товар? (одной фразой)' },
        { kind: 'textarea', name: 'customer_before', label: 'Что покупатель чувствует ДО покупки', placeholder: 'например — устала искать качественную базу, всё либо дёшево, либо дорого' },
        { kind: 'textarea', name: 'customer_after', label: 'Что покупатель чувствует ПОСЛЕ покупки', placeholder: 'например — наконец-то простой утренний выбор, всё сочетается' },
        { kind: 'text', name: 'customer_main_segment', label: 'Если у вас несколько сегментов — какой главный?' },
      ],
    },
    {
      key: 'tone',
      label: 'Раздел 3',
      title: 'Тон и стиль',
      fields: [
        { kind: 'radio', name: 'tone_address', label: 'Обращение', grid: 3, options: ['ты', 'вы', 'зависит от канала'] },
        { kind: 'radio', name: 'tone_emoji', label: 'Эмодзи', grid: 2,
          options: ['да, активно', 'умеренно (1–2 на пост)', 'почти нет', 'запрещены'] },
        { kind: 'radio', name: 'tone_humor', label: 'Юмор', grid: 3,
          options: ['да, любим', 'только лёгкий', 'серьёзный тон'] },
        { kind: 'radio', name: 'brand_position', label: 'Позиция бренда (выберите одно главное)', grid: 1,
          options: [
            { value: 'Эксперт', label: '<b>Эксперт</b> — учим, объясняем' },
            { value: 'Друг', label: '<b>Друг</b> — на одной волне с покупателем' },
            { value: 'Наставник', label: '<b>Наставник</b> — ведём за руку' },
            { value: 'Премиум-производитель', label: '<b>Премиум-производитель</b> — статус, качество' },
            { value: 'Бунтарь', label: '<b>Бунтарь</b> — против шаблонов в нише' },
            { value: 'Другое', label: 'Другое' },
          ],
          extra: { kind: 'text', placeholder: 'Если «другое» — укажите' } },
        { kind: 'textarea', name: 'inspiring_brands', label: '2–3 бренда / блогера, чей стиль вам нравится', hint: 'Любая ниша, не только конкуренты.' },
        { kind: 'textarea', name: 'inspiring_what_likes', label: 'Что именно нравится в их коммуникации', placeholder: 'например — короткие посты без воды, честные обзоры' },
        { kind: 'group', title: 'Стоп-лист — то, чего НЕ должно быть в контенте', fields: [
          { kind: 'text', name: 'stop_words', label: 'Слова', placeholder: 'например — "красотка", "девочки", "успех"' },
          { kind: 'text', name: 'stop_topics', label: 'Темы', placeholder: 'например — политика, диеты, отношения' },
          { kind: 'text', name: 'stop_formats', label: 'Форматы', placeholder: 'например — танцы под трендовую музыку, обзоры конкурентов' },
        ] },
      ],
    },
    {
      key: 'product',
      label: 'Раздел 4',
      title: 'Ассортимент и ценник',
      fields: [
        { kind: 'text', name: 'product_category', label: 'Точная категория на МП', placeholder: 'например — Женское / Платья / Повседневные' },
        { kind: 'textarea', name: 'product_locomotive', label: 'Товар-локомотив (тот, что приносит больше всего денег)', hint: 'Название + 1 предложение.' },
        { kind: 'radio', name: 'locomotive_share', label: 'Доля локомотива в обороте', grid: 2,
          options: ['>50%', '30–50%', '<30%', 'не знаю'] },
        { kind: 'radio', name: 'total_sku', label: 'Всего активных SKU', grid: 2,
          options: ['1–10', '10–50', '50–200', '200+'] },
        { kind: 'radio', name: 'segment', label: 'Сегмент', grid: 1,
          options: [
            { value: 'Масс-маркет', label: '<b>Масс-маркет</b> — конкурируем по цене' },
            { value: 'Средний', label: '<b>Средний</b> — баланс цена/качество' },
            { value: 'Премиум', label: '<b>Премиум</b> — покупают за качество и бренд' },
          ] },
        { kind: 'text', name: 'average_check', label: 'Средний чек, ₽', placeholder: 'например — 2 500' },
      ],
    },
    {
      key: 'channels',
      label: 'Раздел 5',
      title: 'Каналы',
      description: 'Для каждого канала отметьте статус и заполните, если есть данные. Можно пропускать.',
      fields: [
        { kind: 'channels', name: 'channels', items: [
          { key: 'telegram',  name: 'Telegram' },
          { key: 'instagram', name: 'Instagram' },
          { key: 'vk',        name: 'VK' },
          { key: 'pinterest', name: 'Pinterest' },
          { key: 'youtube',   name: 'YouTube/Дзен/др' },
        ] },
        { kind: 'text', name: 'first_channel', label: 'Если каналов пока нет — с какого хотите начать первым?' },
        { kind: 'radio', name: 'vertical_video', label: 'Готовы снимать вертикальные видео (Reels/Shorts)?', grid: 1,
          options: [
            'Да, можем снимать сами',
            'Только с подрядчиком',
            'Нет, видео не делаем — только фото и тексты',
          ] },
      ],
    },
    {
      key: 'goals',
      label: 'Раздел 6',
      title: 'Цели и метрики',
      fields: [
        { kind: 'checkbox', name: 'main_goals', label: 'Главные цели (1–2)', grid: 1,
          options: [
            { value: 'Прямые продажи через канал', label: '<b>Прямые продажи через канал</b> — подписчики покупают на МП' },
            { value: 'Прогрев в рассылку / лидмагнит', label: '<b>Прогрев в рассылку / лидмагнит</b> — собираем базу, продаём через сообщения' },
            { value: 'Снижение зависимости от рекламы МП', label: '<b>Снижение зависимости от рекламы МП</b> — свой трафик-источник' },
            { value: 'Построение бренда', label: '<b>Построение бренда</b> — узнаваемость, ценность бизнеса' },
            { value: 'Удержание клиентов', label: '<b>Удержание клиентов</b> — повторные покупки, лояльность' },
          ],
          otherText: 'другое — укажите' },
        { kind: 'radio', name: 'goal_3_months', label: 'Через 3 месяца реально получить', grid: 1,
          options: [
            '500–1500 подписчиков в основном канале',
            '1500–3000 подписчиков',
            '3000+ подписчиков',
            'Не цель, важнее заявки/продажи',
          ],
          otherText: 'если важнее заявки — укажите цифру' },
        { kind: 'radio', name: 'goal_6_months', label: 'Через 6 месяцев', grid: 1,
          options: [
            'Стабильный поток заявок 5–10/мес',
            'Стабильный поток 10–30/мес',
            '30+ заявок в месяц',
            'Не цель, важнее охват/узнаваемость',
          ] },
      ],
    },
    {
      key: 'assets',
      label: 'Раздел 7',
      title: 'Активы и команда',
      fields: [
        { kind: 'checkbox', name: 'content_assets', label: 'Контентные активы (отметьте, что есть)', grid: 1,
          options: [
            'Фотобанк товаров',
            'Видео распаковок / обзоров',
            'Отзывы клиентов (текстом или видео)',
            'Лайфстайл-съёмки (товар в жизни, на людях)',
            'Съёмки производства / упаковки',
            'UGC от покупателей (фото/видео клиентов)',
            'Готовых активов нет — стартуем с нуля',
          ] },
        { kind: 'textarea', name: 'assets_details', label: 'Подробности по активам (количество, качество, ссылки)', placeholder: 'например — 200 фото товаров на белом фоне, 30 лайфстайл-кадров, есть 5 видеоотзывов' },
        { kind: 'group', title: 'Команда — кто что делает сейчас', fields: [
          { kind: 'text', name: 'team_writer', label: 'Тексты пишет' },
          { kind: 'text', name: 'team_videographer', label: 'Снимает / монтирует видео' },
          { kind: 'text', name: 'team_publisher', label: 'Публикует и отвечает на комментарии' },
          { kind: 'text', name: 'content_budget', label: 'Бюджет на контент в месяц (по желанию)' },
        ] },
        { kind: 'radio', name: 'who_publishes', label: 'Кто будет публиковать готовые посты?', grid: 1,
          options: [
            'Я сам / помощник — буду брать тексты и публиковать вручную',
            'Наш SMM-щик — он будет работать с готовыми материалами',
            'Хотим передать публикацию вам — нужны доступы к каналам (+10к/мес к тарифу)',
          ] },
        { kind: 'textarea', name: 'pain_time_eater', label: 'Что съедает больше всего времени? (честно)' },
        { kind: 'textarea', name: 'pain_doesnt_work', label: 'Что вообще не получается?' },
      ],
    },
    {
      key: 'season',
      label: 'Раздел 8',
      title: 'Сезонность и планы',
      fields: [
        { kind: 'text', name: 'peak_months', label: 'Пиковые месяцы продаж', placeholder: 'например — ноябрь, декабрь, март' },
        { kind: 'text', name: 'low_months', label: 'Месяцы провала' },
        { kind: 'textarea', name: 'upcoming_launches', label: 'Запуски / новинки / коллекции в ближайшие 3 месяца',
          hint: 'Даже на уровне идеи, с примерными датами.', placeholder: '1. ...\n2. ...\n3. ...' },
        { kind: 'checkbox', name: 'marketplace_sales', label: 'Какие распродажи МП планируете отрабатывать', grid: 2,
          options: ['11.11', 'Чёрная Пятница', 'Новогодние акции', '8 марта', 'Сезонные распродажи МП'],
          otherText: 'другое — укажите' },
      ],
    },
  ],
};
